name: Grujin
description: A simple offline password generator.
dependencies:
    polymer: ">=0.11.0+5 <0.12.0"
    core_elements: ">=0.0.6 <0.1.0"
    paper_elements: ">=0.0.1 <0.1.0"
    crypto: ">=0.9.0"
    cipher: ">=0.7.0 <0.8.0"
    lawndart: ">=0.6.5 <0.7.0"
    chrome: any
transformers:
- chrome
- polymer:
    entry_points: 
    - web/grujin.html