name: Paper Safe
description: The simple login utility.
dependencies:
    polymer: ">=0.12.0 <0.13.0"
    core_elements: ">=0.1.1 <0.2.0"
    paper_elements: ">=0.1.0+2 <0.2.0"
    crypto: ">=0.9.0"
    cipher: ">=0.7.0 <0.8.0"
    lawndart: ">=0.6.5 <0.7.0"
    chrome: ">=0.6.0 <0.7.0"
transformers:
- polymer:
    entry_points: 
    - web/grujin.html
    csp: true
- chrome